//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatveevaLearnSpas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlQuestion
    {
        public int Id { get; set; }
        public int IdSection { get; set; }
        public string Question { get; set; }
        public string CorrectAnswer { get; set; }
        public string InCorrectAnswer { get; set; }
        public string InCorrectAnswerTwo { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
