//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatveevaLearnSpas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testing
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdSection { get; set; }
        public bool Status { get; set; }
        public System.DateTime DateTesting { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual User User { get; set; }
    }
}
